### PR TITLE
Providerloginfix

### PR DESCRIPTION
**Pull request by garussell**
### Description of changes

Fixed broken tests, removed provider login function after we decided we are using enums on the front end with one user table, different user levels.

### Test Suite
- [x] Are all tests within the test suite passing?

### CODE REVIEW

**Review by kcockett — CHANGES_REQUESTED** [review]
This does not look correct.  There are 15 failed tests at this time.  Check the code and try again.

**Review by z-fitch — APPROVED** [review]

**Review by garussell — COMMENTED** [review]
Should be fixed.  There were issues with migrations

**Review by garussell — COMMENTED** [review]
there were migration issues, should be fixed now

**Review by z-fitch — APPROVED** [review]

**Review by kcockett — APPROVED** [review]
Tests are passing and Search API is working

**Pull request merged**
